version: "2"
checks:
  argument-count:
    config:
      threshold: 7
  method-complexity:
    config:
      threshold: 15
plugins:
  pep8:
    enabled: true
  radon:
    enabled: true
  sonar-python:
    enabled: true
exclude_patterns:
- build/
