language: bash

env:
- MAUZR_VERSION=${TRAVIS_TAG#v}

services:
- docker

stages:
- test
- name: distribute
  if: tag =~ ^v\d{6}.\d\d?$
- name: dockerize
  if: tag =~ ^v\d{6}.\d\d?$

jobs:
  include:
  - stage: test
    script:
    - docker run -v $PWD:/opt/mauzr eqrx/mauzr-build:x86 ./setup.py pytest build_sphinx
  - stage: distribute
    script:
    - docker run -v $PWD:/opt/mauzr eqrx/mauzr-build:x86 ./setup.py build_sphinx sdist bdist_wheel
    after_success:
    - docker run -v $PWD:/opt/mauzr eqrx/mauzr-build:x86 twine upload -u "$PYPI_USER" -p "$PYPI_PASSWD" dist/*
    - sudo chown $(whoami) -R $PWD
    - tar -zc -f doc.tar.gz -C build/sphinx html
    - echo "mauzr.eqrx.net" > build/sphinx/html/CNAME
    - touch build/sphinx/html/.nojekyll
    deploy:
    - provider: pages
      on:
        tags: true
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      local_dir: build/sphinx/html
    - provider: releases
      on:
        tags: true
      overwrite: true
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file_glob: true
      file:
      - doc.tar.gz
      - dist/*
  - stage: distribute
    before_script:
    - mkdir -p build/esp32
    script:
    - docker run -v $PWD:/opt/mauzr eqrx/mauzr-build:esp32 \
      "make BOARD=SIPY && make BOARD=WIPY && make BOARD=DEVKITC"
    after_success:
    - cp build/esp32/SIPY/release/sipy.bin build/esp32-sipy.bin
    - cp build/esp32/WIPY/release/wipy.bin build/esp32-wipy.bin
    - cp build/esp32/DEVKITC/release/wipy.bin build/esp32-devkitc.bin
    deploy:
    - provider: releases
      on:
        tags: true
      overwrite: true
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file_glob: true
      file:
      - build/esp32-*.bin
  - stage: distribute
    before_script:
    - mkdir -p build/esp82xx
    script:
    - docker run -v $PWD:/opt/mauzr eqrx/mauzr-build:esp82xx make
    before_deploy:
    - cp build/esp82xx/firmware-combined.bin build/esp82xx.bin
    deploy:
    - provider: releases
      on:
        tags: true
      overwrite: true
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file:
      - build/esp82xx.bin
  - stage: dockerize
    before_script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWD"
    script:
    - docker build -t eqrx/mauzr:x86-$MAUZR_VERSION -f .dockerfile --build-arg VCS_REF=$TRAVIS_COMMIT --build-arg VERSION=$MAUZR_VERSION --build-arg BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ) .
    after_success:
    - docker push eqrx/mauzr:x86-$MAUZR_VERSION
