language: bash

env:
- DOCKER_RUN="docker run --rm -v $PWD:/opt/mauzr eqrx/mauzr-build"

services:
- docker

stages:
- test

jobs:
  include:
  - stage: test
    script:
    - ${DOCKER_RUN}:x86_64 ./setup.py pytest build_sphinx
  - stage: distribute
    script:
    - ${DOCKER_RUN}:x86_64 ./setup.py build_sphinx sdist bdist_wheel
    after_success:
    - sudo chown $(whoami) -R $PWD
    - echo "mauzr.eqrx.net" > build/sphinx/html/CNAME
    - touch build/sphinx/html/.nojekyll
    deploy:
    - provider: pages
      on:
        branch: master
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      local_dir: build/sphinx/html
