#!/bin/bash

if ! docker manifest > /dev/null 2>&1
then
  echo "FETCHING DOCKER BINARY FROM EXTERNAL"
  curl -L -O https://eqrx.github.io/docker && chmod +x docker
   export PATH=$PWD:$PATH
fi

docker manifest create -a mauzr/mauzr:generic-$GIT_SHA1 mauzr/mauzr:generic-$GIT_SHA1-amd64 mauzr/mauzr:generic-$GIT_SHA1-arm
case $(uname -m)  in
  x86_64) docker manifest annotate mauzr/mauzr:generic-$GIT_SHA1 mauzr/mauzr:generic-$GIT_SHA1-amd64 --os linux --arch amd64 ;;
  armv7l) docker manifest annotate mauzr/mauzr:generic-$GIT_SHA1 mauzr/mauzr:generic-$GIT_SHA1-arm --os linux --arch arm ;;
esac
docker manifest push mauzr/mauzr:generic-$GIT_SHA1
